version: '3'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: huytheadmin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydict
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
