server:
  host: localhost
  port: 8080
db:
  host: db
  port: 5432
  user: exampleUser
  password: examplePassword
  name: exampleDBName
jwt:
  secret: secretcodeorsomethinglikethat
ocr:
  key: api-key-for-ocr-service